server:
  port: 9090
  
spring:  application:    name: API-GATEWAY
  cloud:    gateway:      routes:      - id: AUTH-SERVICE
        uri: lb://AUTH-SERVICE
        predicates:        - Path=/auth/**
      - id: PATIENT-SERVICE
        uri: lb://PATIENT-SERVICE
        predicates:
        - Path=/patient/**
      - id: DOCTOR-SERVICE
        uri: lb://DOCTOR-SERVICE
        predicates:
        - Path=/doctor/**
      - id: BOOK-SERVICE
        uri: lb://BOOK-SERVICE
        predicates:
        - Path=/book/**
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8961/eureka/
  instance:
    hostname : localhost